version: 2.1
orbs:
  node: circleci/node@1.1.6
  # To use CircleCI orbs, need to enable two settings.
  # - Settings -> Security -> Allow uncertified orbs
  # - Settings -> Advanced Settings -> Enable pipelines
  # https://github.com/cypress-io/circleci-orb#how-to-enable
  cypress: cypress-io/cypress@1
jobs:
  build-and-test:
    executor: 'node/default'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn test
            - run: yarn ci:cy:run
workflows:
  build-and-test:
    jobs:
      - build-and-test
      - cypress/install
      - cypress/run:
          requires:
            - cypress/install
          yarn: true
          start: yarn start
          wait-on: 'http://localhost:3000'
          no-workspace: true
          record: true # # record results to Cypress Dashboard
          # parallel: true # run tests in parallel
          # parallelism: 3 # use 3 CircleCI machines
          # group: 3 machines # name this group "3 machines"
