// mock

import { IUser, Gender, UserType } from 'components/users/IUser'

export const fetchUsers = (): Promise<IUser[]> => {
  return new Promise((resolve) => {
    resolve([
      {
        id: 1,
        name: 'John',
        email: 'john@email.com',
        gender: 'male' as Gender,
        type: 'admin' as UserType,
      },
      {
        id: 2,
        name: 'Bob',
        email: 'bob@email.com',
        gender: 'male' as Gender,
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 4,
        name: 'Maria',
        email:
          'mariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamariamaria@maria.com',
        type: 'admin' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
      {
        id: 3,
        name: 'Mark',
        email: 'mark@email.com',
        type: 'default' as UserType,
      },
    ])
  })
}
